name: Bootcamp_Test_Workflow
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Bootcamp-API\Bootcamp-API.csproj
    - name: Build
      run: dotnet build Bootcamp-API\Bootcamp-API.csproj --no-restore 
    - name: Test
      run: dotnet test Bootcamp-API\Bootcamp-API.csproj --no-build --verbosity normal 